        # -*- coding: utf-8 -*-

        # Form implementation generated from reading ui file 'untitled.ui'
        #
        # Created by: PyQt5 UI code generator 5.15.9
        #
        # WARNING: Any manual changes made to this file will be lost when pyuic5 is
        # run again.  Do not edit this file unless you know what you are doing.


        from PyQt5 import QtCore, QtGui, QtWidgets


        class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1400, 900)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.widget_aselsan_15dk = QtWidgets.QWidget(self.centralwidget)
                self.widget_aselsan_15dk.setGeometry(QtCore.QRect(40, 10, 300, 300))
                self.widget_aselsan_15dk.setObjectName("widget_aselsan_15dk")
                self.frame_aselsan_gunluk = QtWidgets.QFrame(self.centralwidget)
                self.frame_aselsan_gunluk.setGeometry(QtCore.QRect(380, 10, 300, 300))
                self.frame_aselsan_gunluk.setObjectName("frame_aselsan_gunluk")
                self.frame_bist100_gunluk = QtWidgets.QFrame(self.centralwidget)
                self.frame_bist100_gunluk.setGeometry(QtCore.QRect(720, 10, 300, 300))
                self.frame_bist100_gunluk.setObjectName("frame_bist100_gunluk")
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.setGeometry(QtCore.QRect(90, 630, 121, 23))
                self.pushButton.setObjectName("pushButton")
                self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
                self.textEdit.setGeometry(QtCore.QRect(90, 320, 191, 21))
                self.textEdit.setObjectName("textEdit")
                self.frame_aselsan_gunluk_3 = QtWidgets.QFrame(self.centralwidget)
                self.frame_aselsan_gunluk_3.setGeometry(QtCore.QRect(1060, 10, 300, 300))
                self.frame_aselsan_gunluk_3.setObjectName("frame_aselsan_gunluk_3")
                self.gunluk_tahmin = QtWidgets.QLCDNumber(self.centralwidget)
                self.gunluk_tahmin.setGeometry(QtCore.QRect(430, 400, 64, 23))
                self.gunluk_tahmin.setObjectName("gunluk_tahmin")
                self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
                self.textEdit_2.setGeometry(QtCore.QRect(430, 320, 181, 21))
                self.textEdit_2.setObjectName("textEdit_2")
                self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
                self.textEdit_3.setGeometry(QtCore.QRect(790, 320, 181, 21))
                self.textEdit_3.setObjectName("textEdit_3")
                self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
                self.textEdit_5.setGeometry(QtCore.QRect(1100, 320, 181, 21))
                self.textEdit_5.setObjectName("textEdit_5")
                self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_2.setGeometry(QtCore.QRect(90, 510, 121, 23))
                self.pushButton_2.setObjectName("pushButton_2")
                self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_3.setGeometry(QtCore.QRect(90, 550, 121, 23))
                self.pushButton_3.setObjectName("pushButton_3")
                self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
                self.textEdit_4.setGeometry(QtCore.QRect(90, 360, 191, 21))
                self.textEdit_4.setObjectName("textEdit_4")
                self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
                self.textEdit_6.setGeometry(QtCore.QRect(430, 360, 191, 21))
                self.textEdit_6.setObjectName("textEdit_6")
                self.textEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
                self.textEdit_7.setGeometry(QtCore.QRect(350, 500, 191, 21))
                self.textEdit_7.setObjectName("textEdit_7")
                self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_4.setGeometry(QtCore.QRect(90, 590, 121, 23))
                self.pushButton_4.setObjectName("pushButton_4")
                self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_5.setGeometry(QtCore.QRect(790, 360, 121, 23))
                self.pushButton_5.setObjectName("pushButton_5")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(90, 400, 64, 23))
                self.label.setObjectName("label")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 21))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.pushButton.setText(_translate("MainWindow", "Hisse verilerini güncelle"))
                self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Aselsan 15 dakikalık grafiği</span></p></body></html>"))
                self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Aselsan günlük grafiği</span></p></body></html>"))
                self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Bist100 15 dakikalık grafiği</span></p></body></html>"))
                self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Bist100 günlük grafiği</span></p></body></html>"))
                self.pushButton_2.setText(_translate("MainWindow", "tweetleri güncelle"))
                self.pushButton_3.setText(_translate("MainWindow", "tweetleri filtrele"))
                self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Aselsan 15 dakikalık tahmin</span></p></body></html>"))
                self.textEdit_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Aselsan günlük tahmin</span></p></body></html>"))
                self.textEdit_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Güncel tweetler ve sayısı</p></body></html>"))
                self.pushButton_4.setText(_translate("MainWindow", "duygu analizi yap"))
                self.pushButton_5.setText(_translate("MainWindow", "grafikleri güncelle"))
                self.label.setText(_translate("MainWindow", "aselsan15dk"))
